-- BUSINESS_DELEGATE_HR_EMP
CREATE TABLE "SYSTEM"."BUSINESS_DELEGATE_HR_EMP" 
   	("ENO" NUMBER NOT NULL ENABLE, 
	"ENAME" VARCHAR2(20 BYTE), 
	"DESG" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(20 BYTE), 
	 CONSTRAINT "BUSINESS_DELEGATE_HR_EMP_PK" PRIMARY KEY ("ENO"));

-- BUSINESS_DELEGATE_FINANCE_EMP	 
CREATE TABLE "SYSTEM"."BUSINESS_DELEGATE_FINANCE_EMP" 
   	("ENO" NUMBER NOT NULL ENABLE, 
	"ENAME" VARCHAR2(20 BYTE), 
	"SALARY" NUMBER, 
	"ADDRESS" VARCHAR2(20 BYTE), 
	 CONSTRAINT "BUSINESS_DELEGATE_FINANCE__PK" PRIMARY KEY ("ENO"));

-- BD_ENO_SEQ
CREATE SEQUENCE  "SYSTEM"."BD_ENO_SEQ"  MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;